# Test the netcdf handler with the bes.
#
# $Id: data.1.exp 14588 2006-09-15 21:13:55Z jimg $

global comp_output		# contains output from besstandalone_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir

# The `1' in compare_stdout means call xfail if the test fails.

cedardump_start "data/mfp890505a.cbf"
compare_stdout "cedar/cedardump01.baseline" "cedardump mfp890505a" 0

