# Test the netcdf handler with the bes.
#
# $Id: data.1.exp 14588 2006-09-15 21:13:55Z jimg $

global comp_output		# contains output from besstandalone_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir

# The `1' in compare_stdout means call xfail if the test fails.

nrecords_start "data/jro840626a.cbf"
compare_stdout "cedar/nrecords04.baseline" "nrecords jro840626a" 0 match

