# Test the netcdf handler with the bes.
#
# $Id: data.1.exp 14588 2006-09-15 21:13:55Z jimg $

global comp_output		# contains output from besstandalone_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir

# The `1' in compare_stdout means call xfail if the test fails.

nrecords_start "data/dum870921a.cbf"
compare_stdout "cedar/nrecords03.baseline" "nrecords dum870921a" 0 match

